spring:
  application:
    name: ramengo-api
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: ${DATABASE_URL}
    driverClassName: org.h2.Driver
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  h2:
    console:
      path: /h2
      enabled: true
server:
  port: 8080
api:
  key:
    header:
      name: x-api-key
    value: ${API_KEY_VALUE}
external-api:
  url: https://api.tech.redventures.com.br
  key:
    header:
      name: x-api-key
    value: ${EXTERNAL_API_KEY_VALUE}