spring:
  application:
    name: ramen-go
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:h2:mem:banco
    driverClassName: org.h2.Driver
    username: admin
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  h2:
    console:
      path: /h2
      enabled: true
server:
  port: 8080
api:
  key:
    header:
      name: x-api-key
    value: ZtVdh8XQ2U8pWI2gmZ7f796Vh8GllXoN7mr0djNf
external-api:
  url: https://api.tech.redventures.com.br
  key:
    header:
      name: x-api-key
    value: ZtVdh8XQ2U8pWI2gmZ7f796Vh8GllXoN7mr0djNf